// Selection des elements

const video_player = document.querySelector("#video_player"),
  mainVideo = video_player.querySelector("#main-video"),
  progressAreaTime = video_player.querySelector(".progressAreaTime"),
  playingAction = video_player.querySelector(".playing"),
  nextAction = video_player.querySelector(".next"),
  muteAction = video_player.querySelector(".mute"),
  ccAction = video_player.querySelector(".cc"),
  speedAction = video_player.querySelector(".speed"),
  pipAction = video_player.querySelector(".pip"),
  fullscreenAction = video_player.querySelector(".fulscreen"),
  controls = video_player.querySelector(".controls"),
  progressArea = video_player.querySelector(".progress-area"),
  progressBar = video_player.querySelector(".progress-bar"),
  bufferedBar = video_player.querySelector(".buffered-progress-bar"),
  fast_rewind = video_player.querySelector(".skip-back"),
  play_pause = video_player.querySelector(".play_pause"),
  pause = video_player.querySelector(".pause-icon"),
  play = video_player.querySelector(".play-icon"),
  rePlay = video_player.querySelector(".replay-icon"),
  fast_forward = video_player.querySelector(".skip-fore"),
  volume = video_player.querySelector(".volume"),
  volumeHigh = video_player.querySelector(".volume-high-icon"),
  volumeLow = video_player.querySelector(".volume-low-icon"),
  volumeMuted = video_player.querySelector(".volume-muted-icon"),
  volume_range = video_player.querySelector(".volume_range"),
  current = video_player.querySelector(".current"),
  totalDuration = video_player.querySelector(".duration"),
  auto_play = video_player.querySelector(".auto-play"),
  closed_caption = document.querySelector('.closed-caption'),
  settingsBtn = video_player.querySelector(".settingsBtn"),
  picture_in_picture = video_player.querySelector(".picture_in_picture"),
  fullscreen = video_player.querySelector(".fullscreen"),
  exitFullscreen = video_player.querySelector(".exitFullscreen"),
  settings = video_player.querySelector(".settings"),
  loopToggle = video_player.querySelector(".loop-line"),
  playback = video_player.querySelectorAll("#speed-drop li"),
  quality_ul = video_player.querySelector("#quality-drop ul"),
  captions_labels = video_player.querySelector("#captions-drop ul"),
  captions = video_player.querySelector("#captions-drop"),
  tracks = video_player.querySelectorAll("track"),
  loader = video_player.querySelector(".loader");
    var menu_bar = document.querySelector(".menu-bar");
    var settings_item = document.querySelectorAll(".drop-item");
    var home_items = document.querySelectorAll(".drop-item");
    var back_icon = document.querySelectorAll(".back-icon");
    const captionToggle = document.querySelector(".caption-line");
    const qualities = video_player.querySelectorAll("source[sizes]");